### ISSUE TITLE
FYI: A complete terminal keyboard protocol

### ISSUE THREAD

**Issue by kovidgoyal** [CyberShadow/term-keys#1]
https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc#keyboard-handling

**Comment by CyberShadow** [comment]
Thanks; I'm not really sure what to do with this though. Seems like yet another protocol extension proposal to add to the list of xterm's `modifyOtherKeys` and notty.

Also, that's not the ["Kitty" terminal emulator](http://www.9bis.net/kitty/) I was thinking of... any relation? If not, then perhaps a more unique name would be better...

**Comment by kovidgoyal** [comment]
notty is dead and xterm's modifyOtherKeys is underspecified/undocumented and in common with most of xterm's extensions, not queryable. You basically have to read the xterm source code. Just informing you, since you took the trouble to collect existing keyboard extension proposals.

**Comment by CyberShadow** [comment]
I'll add it to the list :)
