### ISSUE TITLE
[RFE] Support wezterm

### ISSUE THREAD

**Issue by Lenbok** [CyberShadow/term-keys#11]
[Wezterm](https://github.com/wez/wezterm) is a nice configurable cross platform terminal emulator. I'd be so happy if we could get the missing terminal keys working under it (I'm looking at you, `C-M-S-v`).

**Comment by CyberShadow** [comment]
Looks doable. If you want to have a go at it, it shouldn't be too difficult - here is one commit which adds support for a terminal emulator:

https://github.com/CyberShadow/term-keys/commit/9584a86d6b014942c074eccbaeff8abc9c697686

**Comment by Lenbok** [comment]
Apparently wezterm supports kitty key sequences, so I've started creating a version based on `term-keys-kitty.el` that is working for keys with simple names. I think I need to create a new column in `term-keys/mapping` to give the name that wezterm expects for each of the keys, since none of the existing columns have the right names for all the keys.

**Comment by rbutoi** [comment]
I'm getting some `~32` and non-working M-SPC et al in the buffer since Wezterm started supporting `modifyOtherKeys` (https://github.com/wez/wezterm/issues/2527) - does this support need updating here?
