### ISSUE TITLE
[Question] How to make ALT+d work in kitty?

### ISSUE THREAD

**Issue by failable** [CyberShadow/term-keys#13]
Hi, thanks for the great package. 

I'm trying to make ALT+d/ALT+w work like GUI emacs. Is adding a `"d"` or `"w"` [here](https://github.com/CyberShadow/term-keys/blob/master/term-keys.el#L330) sufficient? It does not work though.

Thank you.

**Comment by CyberShadow** [comment]
By `ALT`, do you mean the physical PC keyboard key which is usually labeled as "Alt" but in the UNIX world (including Emacs) is referred to as Meta, or do you mean the modifier which the UNIX world refers to as "Alt" but is usually not mapped to any PC keyboard key?

In the first case, these combinations are representable in the standard terminal protocol, no special configuration or packages like term-keys should be needed to make it work.

In the second case, you probably want to remove this line from your copy of the function:

https://github.com/CyberShadow/term-keys/blob/c6b01eed4c44ee45b8bbe7f2f2dee3b1f9119469/term-keys.el#L323

then, configure your terminal emulator accordingly.

**Comment by failable** [comment]
Hi, I on a mac and have the following config in my .emacs.

```
(setq mac-command-modifier 'meta)
(setq mac-option-modifier 'super)
(setq mac-control-modifier 'control)
```

Then by `ALT`, I mean the `command` key on a mac keyboard. So I think it's the first case. But when I press `command + d`, I see text `0;9u` in a kitty terminal instead of running `kill-word` like in a GUI emacs.

I'm not sure whether the above setting is needed for terminal Emacs. But removing them I get the same behavior.

**Comment by CyberShadow** [comment]
I think those options only affect the graphical interface of Emacs, and not the terminal. Applications running in terminal emulators have no awareness of platform-specific keys like "command" / "option".

This is something that likely lies in the domain of the terminal emulator. I see that [Kitty/GLFW treats "command" as super, and "option" as alt (meta)](https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts).

If your goal is to just swap these modifiers around, I don't see any mention in the documentation that it's possible to remap just the modifier keys. I suppose you certainly could use term-keys to fully remap all keys involving these modifiers; I would phrase `term-keys/want-key-p-func` as maybe `(or meta control)` and then configure `term-keys/glfw-modifier-map` to your preference.

**Comment by failable** [comment]
Hi, my goal is not to swap these keys but to get `"ALT" + d` work. Either `option` or `command` key on a mac keyboard is fine for me. But for now neither works for me.

<img width="325" alt="Screen Shot 2022-08-22 at 21 01 57" src="https://user-images.githubusercontent.com/5475262/185927645-a059f64f-777d-4f23-88d6-9c72f9b1a54a.png">

My full config for a `emacs -q -l test.el` session is 

```
;; -*- lexical-binding: t; -*-

(add-to-list 'load-path "/Users/Maximin/Downloads/term-keys/")
(require 'term-keys)
(term-keys-mode t)

(require 'term-keys-kitty)
(with-temp-buffer
  (insert (term-keys/kitty-conf))
  (write-region (point-min) (point-max) "~/kitty-for-term-keys.conf"))
```

**Comment by CyberShadow** [comment]
Then I think you just want to enable [`macos_option_as_alt`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt) in Kitty.

**Comment by failable** [comment]
> Then I think you just want to enable [macos_option_as_alt](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_option_as_alt) in Kitty.

Works now, thank you!
