### ISSUE TITLE
support for gnu screen

### ISSUE THREAD

**Issue by playdougher** [CyberShadow/term-keys#17]
I usually ssh to remote server and always use gnu screen to manage all terminals, Is it possible to support it?

**Comment by CyberShadow** [comment]
Two ways to think about this:

1. Teach GNU screen about all possible keyboard combinations on modern PC keyboards, both on the sending and receiving side. I don't think it's possible without significant changes to its code: https://www.gnu.org/software/screen/manual/html_node/Input-Translation.html#Input-Translation

2. Make GNU screen ignore these sequences and just pass them through.

What happens if you try to configure Emacs and your terminal as if you weren't using GNU screen?

**Comment by playdougher** [comment]
> Two ways to think about this:
> 
>     1. Teach GNU screen about all possible keyboard combinations on modern PC keyboards, both on the sending and receiving side. I don't think it's possible without significant changes to its code: https://www.gnu.org/software/screen/manual/html_node/Input-Translation.html#Input-Translation

Yes, change code is not  a good solution, usually we can't update gnu screen in remote customer server

>     2. Make GNU screen ignore these sequences and just pass them through.

I think it's a good idea.

> What happens if you try to configure Emacs and your terminal as if you weren't using GNU screen?

I tried to configure Emacs and my local urxvt, it works. I'm using urxvt.

When I run ` sh ~/launch-urxvt-with-term-keys.sh -e emacs -nw` locally, emacs can set mark as expected when I press `C-S-p`.
When I run `screen` and run `sh ~/launch-urxvt-with-term-keys.sh -e emacs -nw`, emacs can set mark as expected when I press `C-S-p` too.
So I think gnu screen won't change escape sequence of `C-S-p` that urxvt pass to screen.

But when I run `ssh localhost`, then `sh ~/launch-urxvt-with-term-keys.sh -e emacs -nw`, it shows "urxvt: can't open display as no -display option has been given and DISPLAY is not set, aborting.". I think the reason is I don't enable ssh X forwarding, so it can't open urxvt. But I don't want to X forwarding to open any terminal emulator, it's often slow. 
I want to use the "ssh terminal" directly, which means I want to run `ssh <remote host>` then `screen` then `emacs`, then I have term-keys worked. So the problem is how to pass term-keys keysym to "ssh terminal". I'm figuring out what's the "ssh terminal", it seems it's not any of terminal emulator

**Comment by CyberShadow** [comment]
`ssh` is just a program that runs in a terminal emulator, like `screen` or `emacs -nw`. So, try `launch-urxvt-with-term-keys.sh`, then in that terminal, `ssh localhost` then `screen` then `emacs -nw`.

(Closing this because no change is needed in term-keys.)

**Comment by playdougher** [comment]
yes, lauch urxvt with launch-urxvt-with-term-keys.sh then ssh works, but it will make all programs running in urxvt use term-keys keysym and has some collision like ^\ will be interpreted as ^[^_F"^_, so gnu screen can't get ^\, I try delete the keysym in ~/launch-urxvt-with-term-keys.sh and it works good
```
zh@dust|/home/zh|$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[^_F"^_ 	 27 0033 0x1b
 	 31 0037 0x1f
 	 70 0106 0x46
 	 34 0042 0x22
 	 31 0037 0x1f
```

**Comment by CyberShadow** [comment]
> but it will make all programs running in urxvt use term-keys keysym

Yeah, you would probably want to set something up so that the only programs run in `launch-urxvt-with-term-keys.sh` are SSH, screen, and Emacs.
