### ISSUE TITLE
(term-keys-mode t) and (term-keys/init) errors

### ISSUE THREAD

**Issue by max0x7ba** [CyberShadow/term-keys#2]
When I run `(term-keys-mode t)` or `(term-keys/init)` that results in error `"Symbol's function definition is void: bool-vector"`.

This happens in emacs-25.3.

**Comment by CyberShadow** [comment]
`bool-vector` was added in 2014:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2bcf0551dff645b8c691290adf58dc890b79e745

Any idea why it is absent in your Emacs?

**Comment by max0x7ba** [comment]
I removed `.emacs.d` folder and re-installed `term-keys` it and that fixed this issue.
