### ISSUE TITLE
C-M-% for query-replace-regexp does not work

### ISSUE THREAD

**Issue by max0x7ba** [CyberShadow/term-keys#3]
`C-M-%` runs the command `query-replace-regexp` in the GUI version of emacs. But it does not work when emacs is started in Konsole.

I followed the instructions, configured emacs and Konsole. However, emacs still does not recognise `C-M-%` (Ctrl+Alt+Shift+5) combination. It looks like this combination is missing in `~/.local/share/konsole/Emacs.keytab`.

How do I make `C-M-%` work in emacs with Konsole please?

**Comment by CyberShadow** [comment]
> It looks like this combination is missing in `~/.local/share/konsole/Emacs.keytab`.

It is there, for the default configuration:

```
key 5+Shift+Ctrl+Alt-Meta : "\x1B\x1F\x2E\x27\x1F"
```

As to why Konsole does not pick it up, is a different question... perhaps it expects pre-shifted character (% instead of 5 or 5+Shift), but that didn't seem to work either.

Finding the answer will probably involve digging in Konsole's source code...

**Comment by CyberShadow** [comment]
https://phabricator.kde.org/D10939

**Comment by CyberShadow** [comment]
@max0x7ba The fix should have shipped in Konsole 18.08. Can you check if this is still an issue?

**Comment by CyberShadow** [comment]
I assume that this has been resolved.

**Comment by max0x7ba** [comment]
> @max0x7ba The fix should have shipped in Konsole 18.08. Can you check if this is still an issue?

I didn't have access to Konsole 18.08 in my corporate environment when you closed it.

I am going to give it another try with my current Konsole version 21.12.2 in KDE neon 5.24.

**Comment by max0x7ba** [comment]
I am trying this out again with Konsole version 21.12.2 and Emacs 26.3 in KDE neon 5.24.

I open Konsole and run `emacs -nw`. Emacs gets my ctrl-alt-shift-5 keystroke as alt-shift-5. So, I guess, something goes wrong in Konsole or in Konsole to emacs keystroke passing. Not sure how to narrow the issue down.

**Comment by CyberShadow** [comment]
Could you please post the generated `~/.local/share/konsole/Emacs.keytab` ?

**Comment by max0x7ba** [comment]
`Emacs.keytab` attached.

**Comment by max0x7ba** [comment]
[Emacs.keytab.zip](https://github.com/CyberShadow/term-keys/files/8045370/Emacs.keytab.zip)

**Comment by CyberShadow** [comment]
Please update term-keys to the latest version and regenerate the keytab. I made a fix earlier today for the number keys being unshifted.

**Comment by CyberShadow** [comment]
@max0x7ba Is it working?

**Comment by max0x7ba** [comment]
The problem still persists with version 20220210.1459.

**Comment by CyberShadow** [comment]
OK, could you please post the generated `~/.local/share/konsole/Emacs.keytab` ?

**Comment by max0x7ba** [comment]
[Emacs.keytab.zip](https://github.com/CyberShadow/term-keys/files/8060746/Emacs.keytab.zip)

**Comment by max0x7ba** [comment]
Actually, ctrl-alt-shift-5 now works locally. But not when I run `emacs -nw` over `ssh`.

**Comment by CyberShadow** [comment]
> But not when I run `emacs -nw` over `ssh`.

Please make sure that the remote Emacs instance has an up-to-date version of `term-keys`, and is configured appropriately.

Sometimes the `term-keys` hook gets reset, and requires disabling and re-enabling `term-keys-mode`.

You could try connecting with `ssh` to `localhost` to narrow down the problem.

**Comment by max0x7ba** [comment]
I have updated `term-keys` on the remote host and now ctrl-alt-shift-5 does go through to the remote emacs. Thank you very much for your efforts.
