### ISSUE TITLE
Question : Super and Hyper keys

### ISSUE THREAD

**Issue by aagon** [CyberShadow/term-keys#7]
Hello Mr. Panteleev, and thank you for having tried to bring lossless keyboard support to terminal emacs.

I have tried term-keys and patched my st with the generated header file.

C-S-* keybindings now work correctly, but Hyper and Super keys are still not taken into account by terminal emacs. Are they supposed to be, or is this a normal state of affairs ? The packages README promises any combination, but super and Hyper are X11 modifiers, so I was wondering.

Thank you in advance,

Aymeric Agon-Rambosson

**Comment by CyberShadow** [comment]
Hi @aagon,

You may need to customize how to map X11 modifier state flags (such as Mod4) to Emacs modifiers (such as Hyper).

Have you tried following the directions at the bottom of https://github.com/CyberShadow/term-keys#st pertaining customization?

**Comment by aagon** [comment]
As far as I can see, the default value of the vector `term-keys/x11-modifier-map`, namely `["Shift" "Control" "Mod1" "Mod4" "Mod3" "Mod5"]`, should map correctly if my `xmodmap` looks like this : 
```
xmodmap:  up to 4 keys per modifier, (keycodes in parentheses):

shift       Shift_L (0x32),  Shift_R (0x3e)
lock
control     Control_L (0x42),  Control_R (0x69)
mod1        Alt_L (0x40),  Meta_L (0xcd)
mod2        Num_Lock (0x4d)
mod3        Hyper_L (0x25)
mod4        Super_L (0x85),  Super_R (0x86),  Super_L (0xce)
mod5        ISO_Level3_Shift (0x5c),  Mode_switch (0xcb)
```

So I did not modify it.

And the generated header files do not seem to contain anything pertaining super or hyper keys : 

[config-term-keys-key.h.txt](https://github.com/CyberShadow/term-keys/files/7154721/config-term-keys-key.h.txt)
[config-term-keys-mappedkeys.h.txt](https://github.com/CyberShadow/term-keys/files/7154727/config-term-keys-mappedkeys.h.txt)

Have you managed to use them ?

**Comment by CyberShadow** [comment]
Have you already customized `term-keys/want-key-p-func`? The default implementation excludes the Super, Hyper and Alt modifiers:

https://github.com/CyberShadow/term-keys/blob/83c7d698f76eec1252c17286a146d14f801518c8/term-keys.el#L246-L249

**Comment by aagon** [comment]
Sorry for the late answer.

Yes, this was one of the very first things I tried. Commenting these three lines correctly builds a much bigger `config-term-keys-key.h`, as expected : 

[config-term-keys-key.h.txt](https://github.com/CyberShadow/term-keys/files/7230327/config-term-keys-key.h.txt)

This does not change the behaviour of emacs. Super and Hyper keypresses are still not picked up.

After further research, this is for a very simple reason : the terminal emulator simply does not send them. `H-n` gets simply transformed into `n` by the terminal emulator, which sends `n` to emacs.

So this has nothing to do with your package at all. Hyper and super keys were simply never supposed to work with your package. For them to work, the protocol of the terminal emulator has to be modified. The most promising proposal in that regard is that of Mr. Goyal that can be found here : https://sw.kovidgoyal.net/kitty/keyboard-protocol/.
 
Since this is a new protocol (albeit attempting to be retrocompatible), applications like emacs that wish to use Hyper and super-based chords will have to interpret the byte sequences accordingly.

Closing, and thanking you again for your time and effort.

Best,

Aymeric Agon-Rambosson

**Comment by CyberShadow** [comment]
> For them to work, the protocol of the terminal emulator has to be modified.

This is what this package does.

Sorry, I haven't investigated why they don't work in this case. I don't use them or st myself.

I'll see if I can find some time to investigate.

**Comment by CyberShadow** [comment]
@aagon 

I have investigated, and aside from two minor blemishes which did not affect the outcome, found no issues.

I conclude that you must have done a mistake in configuring emacs, st, or term-keys somewhere.

If you find the time to revisit it, perhaps you could offer some suggestions for improving the documentation to avoid others from running into the same issues.

Thanks.
