### ISSUE TITLE
C-<backspace> does not work

### ISSUE THREAD

**Issue by Nathan-Furnal** [CyberShadow/term-keys#8]
Hi!

I'm using urxvt and I've done the following : 

Added this to my config after I cloned the repo : 

```elisp
(use-package term-keys
  :load-path "site-lisp/term-keys"
  :if (not window-system)
  :config
  (require 'term-keys-urxvt)
  (term-keys-mode t))
```
Then I've ran the function to create the executable `launch-urxvt-with-term-keys.sh`, all seem to work properly except that `C-<backspace>` seems to call `C-h` instead, which seems to be the default, before the package is even loaded. 

I launch it with an alias,  `ec='sh ~/scripts/launch-urxvt-with-term-keys.sh -e emacs -nw'`

How can I fix this? 

Thanks for your help.

**Comment by CyberShadow** [comment]
Some tests to narrow it down:

1. Do you have something like this in the generated script?

   ```
	-keysym.C-BackSpace \
	string\:[...] \
   ```

2. If you run `cat` instead of `emacs` via the generated script, what do you see when you press Control+Backspace?

**Comment by Nathan-Furnal** [comment]
Sure, 

1.
 ```
 -keysym.C-BackSpace \
string\:\^[\^_3B\^_
```
2.  Running `cat` and then Control+Backspace gives me `^H`

**Comment by CyberShadow** [comment]
> Running `cat` and then Control+Backspace gives me `^H`

So, my guess would be that some other part of urxvt's configuration (possibly, an extension) redefines this combination.

Something that worked for me with a different key combination was to define its `builtin-string` action to the empty string. Try adding this to the generated script:

```
	-keysym.C-BackSpace \
	builtin-string: \
```

Otherwise, I would suggest trying to narrow down your urxvt configuration to find the culprit.

**Comment by Nathan-Furnal** [comment]
Alright, I realized this is not your packages' fault but rather a long standing problem with backspace and delete on Unix. 

The fix was [this SO](https://superuser.com/questions/476809/how-do-i-unbind-ctrlbackspace-in-urxvt) : 

References for the issue : 

https://www.emacswiki.org/emacs/BackspaceKey

https://www.systutorials.com/docs/linux/man/7-urxvt/ [ctrl+f delete]

**Comment by CyberShadow** [comment]
So, for future reference, which solution worked for you?

(And, I'm wondering why I didn't need it...)

**Comment by Nathan-Furnal** [comment]
The accepted answer fixed my problem!
